import { describe, expect, it } from "vitest";
import { getCategoryIcon } from "./category-icon";
import {
  SteeringWheelIcon,
  ShiftKnobIcon,
  WheelSpacerIcon,
  LugNutIcon,
  CenterCapIcon,
  TpmsIcon,
  TireIcon,
  WheelIcon,
  BrakeCaliperIcon,
  BrakeRotorIcon,
  BrakePadIcon,
  BrakeLineIcon,
  BrakeIcon,
  PaintIcon,
  GrilleIcon,
  HoodVentIcon,
  HoodIcon,
  BumperIcon,
  FenderIcon,
  CanardIcon,
  SplitterIcon,
  DiffuserIcon,
  SideSkirtIcon,
  RockerPanelIcon,
  QuarterPanelIcon,
  SpoilerIcon,
  MirrorIcon,
  FogLightIcon,
  TailLightIcon,
  HeadlightIcon,
  UnderglowIcon,
  LightBarIcon,
  TurnSignalIcon,
  AmbientLightIcon,
  TintIcon,
  WindshieldIcon,
  WindowNetIcon,
  WindowIcon,
  RoofRackIcon,
  RoofIcon,
  TrunkIcon,
  DoorIcon,
  DecalIcon,
  AntennaIcon,
  BadgeIcon,
  LicensePlateIcon,
  WiperIcon,
  FuelDoorIcon,
  FuelPumpIcon,
  FuelIcon,
  TowHitchIcon,
  BullBarIcon,
  WinchIcon,
  SnorkelIcon,
  RunningBoardIcon,
  LadderRackIcon,
  TonneauCoverIcon,
  BedlinerIcon,
  ConvertibleTopIcon,
  SkidPlateIcon,
  HeaderIcon,
  ExhaustIcon,
  SwayBarIcon,
  StrutBraceIcon,
  AirSuspensionIcon,
  LiftKitIcon,
  BushingIcon,
  BallJointIcon,
  TieRodIcon,
  SubframeIcon,
  SuspensionIcon,
  IntakeIcon,
  WastegateIcon,
  BovIcon,
  TurboIcon,
  ThrottleBodyIcon,
  CamshaftIcon,
  ValveCoverIcon,
  OilPanIcon,
  SparkPlugIcon,
  IgnitionCoilIcon,
  EngineIcon,
  OilFilterIcon,
  OilCoolerIcon,
  FanIcon,
  ThermostatIcon,
  RadiatorIcon,
  TimingBeltIcon,
  DriveBeltIcon,
  AlternatorIcon,
  StarterIcon,
  DifferentialIcon,
  TransferCaseIcon,
  ClutchIcon,
  TransmissionIcon,
  NitrousIcon,
  BatteryIcon,
  ShiftLightIcon,
  GaugeIcon,
  TuningIcon,
  FuseBoxIcon,
  BoltIcon,
  DashCamIcon,
  BackupCameraIcon,
  NavIcon,
  HeadUnitIcon,
  SubwooferBoxIcon,
  SpeakerIcon,
  AlarmIcon,
  RemoteStartIcon,
  FloorMatIcon,
  PedalIcon,
  HeadlinerIcon,
  ConsoleIcon,
  SunVisorIcon,
  CupHolderIcon,
  FireExtinguisherIcon,
  KillSwitchIcon,
  SeatIcon,
  HarnessIcon,
  RollCageIcon,
  BodyKitIcon,
  WrenchIcon,
} from "@/components/ui/icons";

describe("getCategoryIcon", () => {
  it.each([
    // The exact examples that prompted this — none of these should ever
    // fall back to the generic wrench.
    [null, "Custom Candy Paint Job", PaintIcon],
    [null, "Custom Grill", GrilleIcon],
    [null, "Custom Hood", HoodIcon],

    // Steering & shifting
    [null, "Custom Steering Wheel", SteeringWheelIcon],
    [null, "Wood Grain Shift Knob", ShiftKnobIcon],

    // Wheels, tires & brakes — specific sub-parts must win over the
    // generic wheel/brake icons even though they contain those words.
    [null, "20mm Wheel Spacers", WheelSpacerIcon],
    [null, "Chrome Lug Nuts", LugNutIcon],
    [null, "Wheel Center Caps", CenterCapIcon],
    [null, "TPMS Sensor Replacement", TpmsIcon],
    ["Tires", "Michelin Pilot Sport 4S", TireIcon],
    [null, "18x9.5 +35 Wheels", WheelIcon],
    [null, "Brembo Brake Calipers", BrakeCaliperIcon],
    [null, "Slotted Brake Rotors", BrakeRotorIcon],
    [null, "Ceramic Brake Pads", BrakePadIcon],
    [null, "Stainless Brake Lines", BrakeLineIcon],
    [null, "Big Brake Kit", BrakeIcon],

    // Paint & exterior panels
    [null, "Full Vehicle Vinyl Wrap", PaintIcon],
    [null, "Hood Vent Scoop", HoodVentIcon],
    [null, "Vented Carbon Fiber Hood", HoodIcon],
    [null, "Front Bumper", BumperIcon],
    [null, "Fender Flares", FenderIcon],
    [null, "Front Canards", CanardIcon],
    [null, "Carbon Front Splitter", SplitterIcon],
    [null, "Rear Diffuser", DiffuserIcon],
    [null, "Side Skirt Extensions", SideSkirtIcon],
    [null, "Rocker Panel Extensions", RockerPanelIcon],
    [null, "Quarter Panel Repair", QuarterPanelIcon],
    [null, "GT Wing Spoiler", SpoilerIcon],
    [null, "Carbon Fiber Mirror Caps", MirrorIcon],

    // Lighting
    [null, "LED Fog Lights", FogLightIcon],
    [null, "Smoked Tail Lights", TailLightIcon],
    [null, "LED Headlights", HeadlightIcon],
    [null, "LED Underglow Kit", UnderglowIcon],
    [null, "Roof Light Bar", LightBarIcon],
    [null, "Sequential Turn Signals", TurnSignalIcon],
    [null, "Interior Ambient Lighting", AmbientLightIcon],

    // Glass & roof
    [null, "20% Window Tint", TintIcon],
    [null, "Windshield Replacement", WindshieldIcon],
    [null, "Racing Window Net", WindowNetIcon],
    [null, "Power Window Regulator", WindowIcon],
    [null, "Roof Rack Crossbars", RoofRackIcon],
    [null, "Aftermarket Sunroof", RoofIcon],
    [null, "Trunk Lid Replacement", TrunkIcon],
    [null, "Door Handles", DoorIcon],
    [null, "Racing Stripe Decals", DecalIcon],
    [null, "Shark Fin Antenna", AntennaIcon],
    [null, "Custom Emblem Badge", BadgeIcon],
    [null, "License Plate Frame", LicensePlateIcon],
    [null, "Wiper Blades", WiperIcon],

    // Fuel
    [null, "Fuel Door Cover", FuelDoorIcon],
    [null, "Upgraded Fuel Pump", FuelPumpIcon],
    [null, "Fuel Injectors", FuelIcon],

    // Off-road & utility
    [null, "Tow Hitch Receiver", TowHitchIcon],
    [null, "Front Bull Bar", BullBarIcon],
    [null, "Off-Road Winch", WinchIcon],
    [null, "Snorkel Kit", SnorkelIcon],
    [null, "Running Boards", RunningBoardIcon],
    [null, "Ladder Rack", LadderRackIcon],
    [null, "Tonneau Cover", TonneauCoverIcon],
    [null, "Spray-In Bed Liner", BedlinerIcon],
    [null, "Convertible Soft Top", ConvertibleTopIcon],
    [null, "Skid Plate Armor", SkidPlateIcon],

    // Exhaust & induction
    [null, "Long Tube Headers", HeaderIcon],
    [null, "Cat-Back Exhaust", ExhaustIcon],

    // Suspension & chassis
    [null, "Rear Sway Bar", SwayBarIcon],
    [null, "Front Strut Tower Brace", StrutBraceIcon],
    [null, "Air Suspension Kit", AirSuspensionIcon],
    [null, "2 Inch Lift Kit", LiftKitIcon],
    [null, "Control Arm Bushings", BushingIcon],
    [null, "Ball Joint Replacement", BallJointIcon],
    [null, "Tie Rod Ends", TieRodIcon],
    [null, "Subframe Reinforcement", SubframeIcon],
    ["Suspension", "Coilover Kit", SuspensionIcon],

    // Forced induction
    [null, "Cold Air Intake", IntakeIcon],
    [null, "Turbo Wastegate", WastegateIcon],
    [null, "Blow Off Valve", BovIcon],
    [null, "Stage 2 Turbo Kit", TurboIcon],

    // Engine internals
    [null, "Throttle Body Spacer", ThrottleBodyIcon],
    [null, "Aftermarket Camshaft", CamshaftIcon],
    [null, "Valve Cover Gasket", ValveCoverIcon],
    [null, "Oil Pan Gasket", OilPanIcon],
    [null, "Iridium Spark Plugs", SparkPlugIcon],
    [null, "Ignition Coil Packs", IgnitionCoilIcon],
    [null, "Engine Block Rebuild", EngineIcon],
    [null, "LS3 Motor Swap", EngineIcon],
    [null, "New Motor", EngineIcon],

    // Cooling
    [null, "Oil Filter", OilFilterIcon],
    [null, "Oil Cooler Kit", OilCoolerIcon],
    [null, "Electric Cooling Fan", FanIcon],
    [null, "Thermostat Replacement", ThermostatIcon],
    [null, "Aluminum Radiator", RadiatorIcon],

    // Drivetrain
    [null, "Timing Belt Kit", TimingBeltIcon],
    [null, "Serpentine Belt", DriveBeltIcon],
    [null, "Alternator Replacement", AlternatorIcon],
    [null, "Starter Motor", StarterIcon],
    [null, "Limited Slip Differential", DifferentialIcon],
    [null, "4WD Transfer Case", TransferCaseIcon],
    [null, "Stage 2 Clutch", ClutchIcon],
    [null, "6-Speed Manual Transmission Rebuild", TransmissionIcon],
    [null, "Nitrous Oxide Kit", NitrousIcon],

    // Electrical
    [null, "Lithium Battery", BatteryIcon],
    [null, "Shift Light", ShiftLightIcon],
    [null, "Boost Gauge", GaugeIcon],
    [null, "ECU Tune", TuningIcon],
    [null, "Upgraded Fuse Box", FuseBoxIcon],
    [null, "Wiring Harness Relocation", BoltIcon],

    // Tech & audio
    [null, "Front Dash Cam", DashCamIcon],
    [null, "Backup Camera", BackupCameraIcon],
    [null, "GPS Navigation Unit", NavIcon],
    [null, "Aftermarket Head Unit", HeadUnitIcon],
    [null, "Ported Subwoofer Box", SubwooferBoxIcon],
    [null, "Subwoofer and Amp", SpeakerIcon],
    [null, "Car Alarm System", AlarmIcon],
    [null, "Remote Start Kit", RemoteStartIcon],

    // Interior
    [null, "All-Weather Floor Mats", FloorMatIcon],
    [null, "Performance Pedal Covers", PedalIcon],
    [null, "Replacement Headliner", HeadlinerIcon],
    [null, "Center Console Organizer", ConsoleIcon],
    [null, "Leather Sun Visor", SunVisorIcon],
    [null, "Cup Holder Insert", CupHolderIcon],
    [null, "Fire Extinguisher Mount", FireExtinguisherIcon],
    [null, "Battery Kill Switch", KillSwitchIcon],
    ["Interior", "Recaro Seats", SeatIcon],

    // Safety & racing
    [null, "Racing Harness", HarnessIcon],
    [null, "Roll Cage", RollCageIcon],

    // Catch-all
    [null, "Widebody Kit", BodyKitIcon],

    // Nothing matches — should fall back to the generic wrench, not
    // crash or return something misleading.
    [null, "Some Random Thing", WrenchIcon],
  ] as const)("maps (%s, %s) to the right icon", (category, rawName, expected) => {
    expect(getCategoryIcon(category, rawName)).toBe(expected);
  });
});
